apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.2  # Replace with actual version
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
  - nodePort: 30601
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: NodePort
